services:
    _defaults:
        public: false

    Oro\Bundle\AkeneoBundle\Command\CleanupCommand:
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: console.command }

    Oro\Bundle\AkeneoBundle\Command\CacheClearCommand:
        arguments:
            - '@oro_akeneo.configurable_cache'
        tags:
            - { name: console.command }
